version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ip-allocator-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ip_allocator
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ip-allocator-network

  api:
    build: .
    container_name: ip-allocator-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URI: mongodb://admin:password123@mongodb:27017/ip_allocator?authSource=admin
      DB_NAME: ip_allocator
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      ENV: production
    depends_on:
      - mongodb
    networks:
      - ip-allocator-network

volumes:
  mongodb_data:

networks:
  ip-allocator-network:
    driver: bridge
